export const FD_DRIVER_API_FAIL = "FD_DRIVER_API_FAIL"

// Drivers
export const GET_FD_DRIVERS = "GET_FD_DRIVERS"
export const GET_FD_DRIVERS_FAIL = "GET_FD_DRIVERS_FAIL"
export const GET_FD_DRIVERS_SUCCESS = "GET_FD_DRIVERS_SUCCESS"

// Add Driver
export const ADD_FD_DRIVER = "ADD_FD_DRIVER"
export const ADD_FD_DRIVER_FAIL = "ADD_FD_DRIVER_FAIL"
export const ADD_FD_DRIVER_SUCCESS = "ADD_FD_DRIVER_SUCCESS"

// Get Driver
export const GET_FD_DRIVER = "GET_FD_DRIVER"
export const GET_FD_DRIVER_FAIL = "GET_FD_DRIVER_FAIL"
export const GET_FD_DRIVER_SUCCESS = "GET_FD_DRIVER_SUCCESS"

// Get Driver On Date
export const GET_FD_DRIVER_POST = "GET_FD_DRIVER_POST"
export const GET_FD_DRIVER_POST_FAIL = "GET_FD_DRIVER_POST_FAIL"
export const GET_FD_DRIVER_POST_SUCCESS = "GET_FD_DRIVER_POST_SUCCESS"

// update Driver
export const PUT_FD_DRIVER = "PUT_FD_DRIVER"
export const PUT_FD_DRIVER_FAIL = "PUT_FD_DRIVER_FAIL"
export const PUT_FD_DRIVER_SUCCESS = "PUT_FD_DRIVER_SUCCESS"

// Delete Driver
export const DELETE_FD_DRIVER = "DELETE_FD_DRIVER"
export const DELETE_FD_DRIVER_FAIL = "DELETE_FD_DRIVER_FAIL"
export const DELETE_FD_DRIVER_SUCCESS = "DELETE_FD_DRIVER_SUCCESS"

// Update Multi Driver Status
export const PUT_FD_DRIVERS_STATUS = "PUT_FD_DRIVERS_STATUS"
export const PUT_FD_DRIVERS_STATUS_FAIL = "PUT_FD_DRIVERS_STATUS_FAIL"
export const PUT_FD_DRIVERS_STATUS_SUCCESS = "PUT_FD_DRIVERS_STATUS_SUCCESS"

// Post Pay
export const POST_FD_DRIVER_PAY = "POST_FD_DRIVER_PAY"
export const POST_FD_DRIVER_PAY_SUCCESS = "POST_FD_DRIVER_PAY_SUCCESS"
export const POST_FD_DRIVER_PAY_FAIL = "POST_FD_DRIVER_PAY_FAIL"

export const POST_FD_DRIVER_PAY_ADJUSTMENT = "POST_FD_DRIVER_PAY_ADJUSTMENT"
export const POST_FD_DRIVER_PAY_ADJUSTMENT_SUCCESS =
  "POST_FD_DRIVER_PAY_ADJUSTMENT_SUCCESS"
export const POST_FD_DRIVER_PAY_ADJUSTMENT_FAIL =
  "POST_FD_DRIVER_PAY_ADJUSTMENT_FAIL"

// Document
// Get Documents
export const GET_FD_DRIVER_DOCUMENTS = "GET_FD_DRIVER_DOCUMENTS"
export const GET_FD_DRIVER_DOCUMENTS_SUCCESS = "GET_FD_DRIVER_DOCUMENTS_SUCCESS"
export const GET_FD_DRIVER_DOCUMENTS_FAIL = "GET_FD_DRIVER_DOCUMENTS_FAIL"

// Add Document
export const POST_FD_DRIVER_DOCUMENT = "POST_FD_DRIVER_DOCUMENT"
export const POST_FD_DRIVER_DOCUMENT_SUCCESS = "POST_FD_DRIVER_DOCUMENT_SUCCESS"
export const POST_FD_DRIVER_DOCUMENT_FAIL = "POST_FD_DRIVER_DOCUMENT_FAIL"

// Get Document
export const GET_FD_DRIVER_DOCUMENT = "GET_FD_DRIVER_DOCUMENT"
export const GET_FD_DRIVER_DOCUMENT_SUCCESS = "GET_FD_DRIVER_DOCUMENT_SUCCESS"
export const GET_FD_DRIVER_DOCUMENT_FAIL = "GET_FD_DRIVER_DOCUMENT_FAIL"

// Update Document
export const PUT_FD_DRIVER_DOCUMENT = "PUT_FD_DRIVER_DOCUMENT"
export const PUT_FD_DRIVER_DOCUMENT_SUCCESS = "PUT_FD_DRIVER_DOCUMENT_SUCCESS"
export const PUT_FD_DRIVER_DOCUMENT_FAIL = "PUT_FD_DRIVER_DOCUMENT_FAIL"

// Update Document
export const DELETE_FD_DRIVER_DOCUMENT = "DELETE_FD_DRIVER_DOCUMENT"
export const DELETE_FD_DRIVER_DOCUMENT_SUCCESS =
  "DELETE_FD_DRIVER_DOCUMENT_SUCCESS"
export const DELETE_FD_DRIVER_DOCUMENT_FAIL = "DELETE_FD_DRIVER_DOCUMENT_FAIL"

// Export Drivers
export const EXPORT_DRIVERS = "EXPORT_DRIVERS"
export const EXPORT_DRIVERS_FAIL = "EXPORT_DRIVERS_FAIL"
export const EXPORT_DRIVERS_SUCCESS = "EXPORT_DRIVERS_SUCCESS"

// Import Drivers
export const IMPORT_DRIVERS = "IMPORT_DRIVERS"
export const IMPORT_DRIVERS_FAIL = "IMPORT_DRIVERS_FAIL"
export const IMPORT_DRIVERS_SUCCESS = "IMPORT_DRIVERS_SUCCESS"

//Driver Vehicle Edit
export const EDIT_DRIVER_VEHICLE_INFO = "EDIT_DRIVER_VEHICLE_INFO"
export const EDIT_DRIVER_VEHICLE_INFO_SUCCESS =
  "EDIT_DRIVER_VEHICLE_INFO_SUCCESS"
export const EDIT_DRIVER_VEHICLE_INFO_FAIL = "EDIT_DRIVER_VEHICLE_INFO_FAIL"

//Driver Vehicle UPDATE}
export const UPDATE_DRIVER_VEHICLE_INFO = "UPDATE_DRIVER_VEHICLE_INFO"
export const UPDATE_DRIVER_VEHICLE_INFO_SUCCESS =
  "UPDATE_DRIVER_VEHICLE_INFO_SUCCESS"
export const UPDATE_DRIVER_VEHICLE_INFO_FAIL = "UPDATE_DRIVER_VEHICLE_INFO_FAIL"

//Driver Vehicle List
export const DRIVER_VEHICLE_LIST = "DRIVER_VEHICLE_LIST"
export const DRIVER_VEHICLE_LIST_SUCCESS = "DRIVER_VEHICLE_LIST_SUCCESS"
export const DRIVER_VEHICLE_LIST_FAIL = "DRIVER_VEHICLE_LIST_FAIL"

//Driver Bank INfo
export const DRIVER_BANK_INFO = "DRIVER_BANK_INFO"
export const DRIVER_BANK_INFO_SUCCESS = "DRIVER_BANK_INFO_SUCCESS"
export const DRIVER_BANK_INFO_FAIL = "DRIVER_BANK_INFO_FAIL"

//Driver Bank INfo
export const DRIVER_BANK_INFO_UPDATE = "DRIVER_BANK_INFO_UPDATE"
export const DRIVER_BANK_INFO__UPDATE_SUCCESS =
  "DRIVER_BANK_INFO_UPDATE_SUCCESS"
export const DRIVER_BANK_INFO__UPDATE_FAIL = "DRIVER_BANK_INFO_UPDATE_FAIL"

//Add Services
export const ADD_DRIVER_SERVICES = "ADD_DRIVER_SERVICES"
export const ADD_DRIVER_SERVICES_SUCCESS = "ADD_DRIVER_SERVICES_SUCCESS"
export const ADD_DRIVER_SERVICES_FAIL = "ADD_DRIVER_SERVICES_FAIL"

//Delete services
export const DELETE_DRIVER_SERVICES = "DELETE_DRIVER_SERVICES"
export const DELETE_DRIVER_SERVICES_SUCCESS = "DELETE_DRIVER_SERVICES_SUCCESS"
export const DELETE_DRIVER_SERVICES_FAIL = "DELETE_DRIVER_SERVICES_FAIL"

//Delete Virtual Account

export const DELETE_VIRTUAL_ACCOUNT = "DELETE_VIRTUAL_ACCOUNT"
export const DELETE_VIRTUAL_ACCOUNT_SUCCESS = "DELETE_VIRTUAL_ACCOUNT_SUCCESS"
export const DELETE_VIRTUAL_ACCOUNT_FAIL = "DELETE_VIRTUAL_ACCOUNT_FAIL"
