export const FD_CUISINE_API_FAIL = "FD_CUISINE_API_FAIL"

// Drivers
export const GET_FD_CUISINES = "GET_FD_CUISINES"
export const GET_FD_CUISINES_FAIL = "GET_FD_CUISINES_FAIL"
export const GET_FD_CUISINES_SUCCESS = "GET_FD_CUISINES_SUCCESS"

// Add Driver
export const ADD_FD_CUISINE = "ADD_FD_CUISINE"
export const ADD_FD_CUISINE_FAIL = "ADD_FD_CUISINE_FAIL"
export const ADD_FD_CUISINE_SUCCESS = "ADD_FD_CUISINE_SUCCESS"

// Get Driver
export const GET_FD_CUISINE = "GET_FD_CUISINE"
export const GET_FD_CUISINE_FAIL = "GET_FD_CUISINE_FAIL"
export const GET_FD_CUISINE_SUCCESS = "GET_FD_CUISINE_SUCCESS"

// update Driver
export const PUT_FD_CUISINE = "PUT_FD_CUISINE"
export const PUT_FD_CUISINE_FAIL = "PUT_FD_CUISINE_FAIL"
export const PUT_FD_CUISINE_SUCCESS = "PUT_FD_CUISINE_SUCCESS"

// Delete Driver
export const DELETE_FD_CUISINE = "DELETE_FD_CUISINE"
export const DELETE_FD_CUISINE_FAIL = "DELETE_FD_CUISINE_FAIL"
export const DELETE_FD_CUISINE_SUCCESS = "DELETE_FD_CUISINE_SUCCESS"

// Update Multi Driver Status
export const PUT_FD_CUISINES_STATUS = "PUT_FD_CUISINES_STATUS"
export const PUT_FD_CUISINES_STATUS_FAIL = "PUT_FD_CUISINES_STATUS_FAIL"
export const PUT_FD_CUISINES_STATUS_SUCCESS = "PUT_FD_CUISINES_STATUS_SUCCESS"

// Export FdCuisines
export const EXPORT_FD_CUISINES = "EXPORT_FD_CUISINES"
export const EXPORT_FD_CUISINES_FAIL = "EXPORT_FD_CUISINES_FAIL"
export const EXPORT_FD_CUISINES_SUCCESS = "EXPORT_FD_CUISINES_SUCCESS"
