export const CAMPAIGN_API_FAIL = "CAMPAIGN_API_FAIL"

// Campaigns
export const GET_CAMPAIGNS = "GET_CAMPAIGNS"
export const GET_CAMPAIGNS_FAIL = "GET_CAMPAIGNS_FAIL"
export const GET_CAMPAIGNS_SUCCESS = "GET_CAMPAIGNS_SUCCESS"

// Add campaign
export const ADD_CAMPAIGN = "ADD_CAMPAIGN"
export const ADD_CAMPAIGN_FAIL = "ADD_CAMPAIGN_FAIL"
export const ADD_CAMPAIGN_SUCCESS = "ADD_CAMPAIGN_SUCCESS"

// Get campaign
export const GET_CAMPAIGN = "GET_CAMPAIGN"
export const GET_CAMPAIGN_FAIL = "GET_CAMPAIGN_FAIL"
export const GET_CAMPAIGN_SUCCESS = "GET_CAMPAIGN_SUCCESS"

// update campaign
export const PUT_CAMPAIGN = "PUT_CAMPAIGN"
export const PUT_CAMPAIGN_FAIL = "PUT_CAMPAIGN_FAIL"
export const PUT_CAMPAIGN_SUCCESS = "PUT_CAMPAIGN_SUCCESS"

// Delete campaign
export const DELETE_CAMPAIGN = "DELETE_CAMPAIGN"
export const DELETE_CAMPAIGN_FAIL = "DELETE_CAMPAIGN_FAIL"
export const DELETE_CAMPAIGN_SUCCESS = "DELETE_CAMPAIGN_SUCCESS"

// Update Multi Campaign Status
export const PUT_CAMPAIGNS_STATUS = "PUT_CAMPAIGNS_STATUS"
export const PUT_CAMPAIGNS_STATUS_FAIL = "PUT_CAMPAIGNS_STATUS_FAIL"
export const PUT_CAMPAIGNS_STATUS_SUCCESS = "PUT_CAMPAIGNS_STATUS_SUCCESS"
