export const FD_RESTAURANT_API_FAIL = "FD_RESTAURANT_API_FAIL"

// Faqs
export const GET_FD_RESTAURANTS = "GET_FD_RESTAURANTS"
export const GET_FD_RESTAURANTS_FAIL = "GET_FD_RESTAURANTS_FAIL"
export const GET_FD_RESTAURANTS_SUCCESS = "GET_FD_RESTAURANTS_SUCCESS"

// Add faq
export const ADD_FD_RESTAURANT = "ADD_FD_RESTAURANT"
export const ADD_FD_RESTAURANT_FAIL = "ADD_FD_RESTAURANT_FAIL"
export const ADD_FD_RESTAURANT_SUCCESS = "ADD_FD_RESTAURANT_SUCCESS"

// Get faq
export const GET_FD_RESTAURANT = "GET_FD_RESTAURANT"
export const GET_FD_RESTAURANT_FAIL = "GET_FD_RESTAURANT_FAIL"
export const GET_FD_RESTAURANT_SUCCESS = "GET_FD_RESTAURANT_SUCCESS"


// post and get purpose base

export const GET_FD_RESTAURANT_POST = "GET_FD_RESTAURANT_POST"
export const GET_FD_RESTAURANT_POST_FAIL = "GET_FD_RESTAURANT_POST_FAIL"
export const GET_FD_RESTAURANT_POST_SUCCESS = "GET_FD_RESTAURANT_POST_SUCCESS"

// update faq
export const PUT_FD_RESTAURANT = "PUT_FD_RESTAURANT"
export const PUT_FD_RESTAURANT_FAIL = "PUT_FD_RESTAURANT_FAIL"
export const PUT_FD_RESTAURANT_SUCCESS = "PUT_FD_RESTAURANT_SUCCESS"

// Delete faq
export const DELETE_FD_RESTAURANT = "DELETE_FD_RESTAURANT"
export const DELETE_FD_RESTAURANT_FAIL = "DELETE_FD_RESTAURANT_FAIL"
export const DELETE_FD_RESTAURANT_SUCCESS = "DELETE_FD_RESTAURANT_SUCCESS"

// Clone
export const CLONE_FD_RESTAURANT = "CLONE_FD_RESTAURANT"
export const CLONE_FD_RESTAURANT_FAIL = "CLONE_FD_RESTAURANT_FAIL"
export const CLONE_FD_RESTAURANT_SUCCESS = "CLONE_FD_RESTAURANT_SUCCESS"

// Update Multi Faq Status
export const PUT_FD_RESTAURANTS_STATUS = "PUT_FD_RESTAURANTS_STATUS"
export const PUT_FD_RESTAURANTS_STATUS_FAIL = "PUT_FD_RESTAURANTS_STATUS_FAIL"
export const PUT_FD_RESTAURANTS_STATUS_SUCCESS =
  "PUT_FD_RESTAURANTS_STATUS_SUCCESS"

// Update Settings
export const PUT_FD_RESTAURANT_SETTINGS = "PUT_FD_RESTAURANT_SETTINGS"
export const PUT_FD_RESTAURANT_SETTINGS_SUCCESS =
  "PUT_FD_RESTAURANT_SETTINGS_SUCCESS"
export const PUT_FD_RESTAURANT_SETTINGS_FAIL = "PUT_FD_RESTAURANT_SETTINGS_FAIL"

// Post Pay
export const POST_FD_RESTAURANT_PAY = "POST_FD_RESTAURANT_PAY"
export const POST_FD_RESTAURANT_PAY_SUCCESS = "POST_FD_RESTAURANT_PAY_SUCCESS"
export const POST_FD_RESTAURANT_PAY_FAIL = "POST_FD_RESTAURANT_PAY_FAIL"

export const POST_FD_RESTAURANT_PAY_ADJUSTMENT =
  "POST_FD_RESTAURANT_PAY_ADJUSTMENT"
export const POST_FD_RESTAURANT_PAY_ADJUSTMENT_SUCCESS =
  "POST_FD_RESTAURANT_PAY_ADJUSTMENT_SUCCESS"
export const POST_FD_RESTAURANT_PAY_ADJUSTMENT_FAIL =
  "POST_FD_RESTAURANT_PAY_ADJUSTMENT_FAIL"

// Document
// Get Documents
export const GET_FD_RESTAURANT_DOCUMENTS = "GET_FD_RESTAURANT_DOCUMENTS"
export const GET_FD_RESTAURANT_DOCUMENTS_SUCCESS =
  "GET_FD_RESTAURANT_DOCUMENTS_SUCCESS"
export const GET_FD_RESTAURANT_DOCUMENTS_FAIL =
  "GET_FD_RESTAURANT_DOCUMENTS_FAIL"

// Add Document
export const POST_FD_RESTAURANT_DOCUMENT = "POST_FD_RESTAURANT_DOCUMENT"
export const POST_FD_RESTAURANT_DOCUMENT_SUCCESS =
  "POST_FD_RESTAURANT_DOCUMENT_SUCCESS"
export const POST_FD_RESTAURANT_DOCUMENT_FAIL =
  "POST_FD_RESTAURANT_DOCUMENT_FAIL"

// Get Document
export const GET_FD_RESTAURANT_DOCUMENT = "GET_FD_RESTAURANT_DOCUMENT"
export const GET_FD_RESTAURANT_DOCUMENT_SUCCESS =
  "GET_FD_RESTAURANT_DOCUMENT_SUCCESS"
export const GET_FD_RESTAURANT_DOCUMENT_FAIL = "GET_FD_RESTAURANT_DOCUMENT_FAIL"

// Update Document
export const PUT_FD_RESTAURANT_DOCUMENT = "PUT_FD_RESTAURANT_DOCUMENT"
export const PUT_FD_RESTAURANT_DOCUMENT_SUCCESS =
  "PUT_FD_RESTAURANT_DOCUMENT_SUCCESS"
export const PUT_FD_RESTAURANT_DOCUMENT_FAIL = "PUT_FD_RESTAURANT_DOCUMENT_FAIL"

// Update Document
export const DELETE_FD_RESTAURANT_DOCUMENT = "DELETE_FD_RESTAURANT_DOCUMENT"
export const DELETE_FD_RESTAURANT_DOCUMENT_SUCCESS =
  "DELETE_FD_RESTAURANT_DOCUMENT_SUCCESS"
export const DELETE_FD_RESTAURANT_DOCUMENT_FAIL =
  "DELETE_FD_RESTAURANT_DOCUMENT_FAIL"

// Export FdRestaurants
export const EXPORT_FD_RESTAURANTS = "EXPORT_FD_RESTAURANTS"
export const EXPORT_FD_RESTAURANTS_FAIL = "EXPORT_FD_RESTAURANTS_FAIL"
export const EXPORT_FD_RESTAURANTS_SUCCESS = "EXPORT_FD_RESTAURANTS_SUCCESS"

// Import FdRestaurants
export const IMPORT_FD_RESTAURANTS = "IMPORT_FD_RESTAURANTS"
export const IMPORT_FD_RESTAURANTS_FAIL = "IMPORT_FD_RESTAURANTS_FAIL"
export const IMPORT_FD_RESTAURANTS_SUCCESS = "IMPORT_FD_RESTAURANTS_SUCCESS"

// Delete Stripe Connect
export const DELETE_FD_VENDOR_STRIPE_CONNECT = "DELETE_FD_VENDOR_STRIPE_CONNECT"
export const DELETE_FD_VENDOR_STRIPE_CONNECT_FAIL =
  "DELETE_FD_VENDOR_STRIPE_CONNECT_FAIL"
export const DELETE_FD_VENDOR_STRIPE_CONNECT_SUCCESS =
  "DELETE_FD_VENDOR_STRIPE_CONNECT_SUCCESS"
