export const BLOG_TAG_API_FAIL = "BLOG_TAG_API_FAIL"

// BlogTAG
export const GET_BLOG_TAGS = "GET_BLOG_TAGS"
export const GET_BLOG_TAGS_FAIL = "GET_BLOG_TAGS_FAIL"
export const GET_BLOG_TAGS_SUCCESS = "GET_BLOG_TAGS_SUCCESS"

// Add blogTAG
export const ADD_BLOG_TAG = "ADD_BLOG_TAG"
export const ADD_BLOG_TAG_FAIL = "ADD_BLOG_TAG_FAIL"
export const ADD_BLOG_TAG_SUCCESS = "ADD_BLOG_TAG_SUCCESS"

// Get blogTAG
export const GET_BLOG_TAG = "GET_BLOG_TAG"
export const GET_BLOG_TAG_FAIL = "GET_BLOG_TAG_FAIL"
export const GET_BLOG_TAG_SUCCESS = "GET_BLOG_TAG_SUCCESS"

// update blogTAG
export const PUT_BLOG_TAG = "PUT_BLOG_TAG"
export const PUT_BLOG_TAG_FAIL = "PUT_BLOG_TAG_FAIL"
export const PUT_BLOG_TAG_SUCCESS = "PUT_BLOG_TAG_SUCCESS"

// Delete blogTAG
export const DELETE_BLOG_TAG = "DELETE_BLOG_TAG"
export const DELETE_BLOG_TAG_FAIL = "DELETE_BLOG_TAG_FAIL"
export const DELETE_BLOG_TAG_SUCCESS = "DELETE_BLOG_TAG_SUCCESS"

// Update Multi BlogTAG Status
export const PUT_BLOG_TAGS_STATUS = "PUT_BLOG_TAGS_STATUS"
export const PUT_BLOG_TAGS_STATUS_FAIL = "PUT_BLOG_TAGS_STATUS_FAIL"
export const PUT_BLOG_TAGS_STATUS_SUCCESS = "PUT_BLOG_TAGS_STATUS_SUCCESS"
