export const GET_DISPATCH = "GET_DISPATCH"
export const GET_DISPATCH_SUCCESS = "GET_DISPATCH_SUCCESS"
export const GET_DISPATCH_FAIL = " GET_DISPATCH_FAIL"

export const GET_DISPATCH_REQUESTS = "GET_DISPATCH_REQUESTS"
export const GET_DISPATCH_REQUESTS_SUCCESS = "GET_DISPATCH_REQUESTS_SUCCESS"
export const GET_DISPATCH_REQUESTS_FAIL = "GET_DISPATCH_REQUESTS_FAIL"

export const POST_REQUEST_DRIVERS = "POST_REQUEST_DRIVERS"
export const POST_REQUEST_DRIVERS_SUCCESS = "POST_REQUEST_DRIVERS_SUCCESS"
export const POST_REQUEST_DRIVERS_FAIL = "POST_REQUEST_DRIVERS_FAIL"

export const PUT_ASSIGN_DRIVER = "PUT_ASSIGN_DRIVER"
export const PUT_ASSIGN_DRIVER_SUCCESS = "PUT_ASSIGN_DRIVER_SUCCESS"
export const PUT_ASSIGN_DRIVER_FAIL = "PUT_ASSIGN_DRIVER_FAIL"

export const POST_DISPATCH_REQUEST = "POST_DISPATCH_REQUEST"
export const POST_DISPATCH_REQUEST_SUCCESS = "POST_DISPATCH_REQUEST_SUCCESS"
export const POST_DISPATCH_REQUEST_FAIL = "POST_DISPATCH_REQUEST_FAIL"

export const GET_DISPATCH_FARE = "GET_DISPATCH_FARE"
export const GET_DISPATCH_FARE_SUCCESS = "GET_DISPATCH_FARE_SUCCESS"
export const GET_DISPATCH_FARE_FAIL = "GET_DISPATCH_FARE_FAIL"
