export const NOTIFICATION_API_FAIL = "NOTIFICATION_API_FAIL"

// NOTIFICATIONs
export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS"
export const GET_NOTIFICATIONS_FAIL = "GET_NOTIFICATIONS_FAIL"
export const GET_NOTIFICATIONS_SUCCESS = "GET_NOTIFICATIONS_SUCCESS"

// Send NOTIFICATION
export const POST_NOTIFICATION = "POST_NOTIFICATION"
export const POST_NOTIFICATION_FAIL = "POST_NOTIFICATION_FAIL"
export const POST_NOTIFICATION_SUCCESS = "POST_NOTIFICATION_SUCCESS"
