/* USERS */

export const SET_MAP_VIEW_CENTER = "SET_MAP_VIEW_CENTER"
export const SET_MAP_VIEW_CENTER_SUCCESS = "SET_MAP_VIEW_CENTER_SUCCESS"

export const SET_MAP_VIEW_BOUNDS = "SET_MAP_VIEW_BOUNDS"
export const SET_MAP_VIEW_BOUNDS_SUCCESS = "SET_MAP_VIEW_BOUNDS_SUCCESS"

export const GET_MAP_VIEW = "GET_MAP_VIEW"
export const GET_MAP_VIEW_SUCCESS = "GET_MAP_VIEW_SUCCESS"
export const GET_MAP_VIEW_FAIL = "GET_MAP_VIEW_FAIL"

export const ASSIGN_DRIVER = "ASSIGN_DRIVER";
export const ASSIGN_DRIVER_SUCCESS = "ASSIGN_DRIVER_SUCCESS";
export const ASSIGN_DRIVER_FAIL = "ASSIGN_DRIVER_FAIL";

export const MAP_POPUP_DRIVER_LOCATION = "MAP_POPUP_DRIVER_LOCATION"
export const MAP_POPUP_DRIVER_LOCATION_SUCCESS =
  "MAP_POPUP_DRIVER_LOCATION_SUCCESS"
export const MAP_POPUP_DRIVER_LOCATION_FAIL = "MAP_POPUP_DRIVER_LOCATION_FAIL"
