export const FD_ATTRIBUTE_API_FAIL = "FD_ATTRIBUTE_API_FAIL"

// Drivers
export const GET_FD_ATTRIBUTES = "GET_FD_ATTRIBUTES"
export const GET_FD_ATTRIBUTES_FAIL = "GET_FD_ATTRIBUTES_FAIL"
export const GET_FD_ATTRIBUTES_SUCCESS = "GET_FD_ATTRIBUTES_SUCCESS"

// Add Driver
export const ADD_FD_ATTRIBUTE = "ADD_FD_ATTRIBUTE"
export const ADD_FD_ATTRIBUTE_FAIL = "ADD_FD_ATTRIBUTE_FAIL"
export const ADD_FD_ATTRIBUTE_SUCCESS = "ADD_FD_ATTRIBUTE_SUCCESS"

// Get Driver
export const GET_FD_ATTRIBUTE = "GET_FD_ATTRIBUTE"
export const GET_FD_ATTRIBUTE_FAIL = "GET_FD_ATTRIBUTE_FAIL"
export const GET_FD_ATTRIBUTE_SUCCESS = "GET_FD_ATTRIBUTE_SUCCESS"

// update Driver
export const PUT_FD_ATTRIBUTE = "PUT_FD_ATTRIBUTE"
export const PUT_FD_ATTRIBUTE_FAIL = "PUT_FD_ATTRIBUTE_FAIL"
export const PUT_FD_ATTRIBUTE_SUCCESS = "PUT_FD_ATTRIBUTE_SUCCESS"

// Delete Driver
export const DELETE_FD_ATTRIBUTE = "DELETE_FD_ATTRIBUTE"
export const DELETE_FD_ATTRIBUTE_FAIL = "DELETE_FD_ATTRIBUTE_FAIL"
export const DELETE_FD_ATTRIBUTE_SUCCESS = "DELETE_FD_ATTRIBUTE_SUCCESS"

// Update Multi Driver Status
export const PUT_FD_ATTRIBUTES_STATUS = "PUT_FD_ATTRIBUTES_STATUS"
export const PUT_FD_ATTRIBUTES_STATUS_FAIL = "PUT_FD_ATTRIBUTES_STATUS_FAIL"
export const PUT_FD_ATTRIBUTES_STATUS_SUCCESS =
  "PUT_FD_ATTRIBUTES_STATUS_SUCCESS"

// Add term in attribute
export const POST_FD_TERM_IN_ATTRIBUTE = "POST_FD_TERM_IN_ATTRIBUTE"
export const POST_FD_TERM_IN_ATTRIBUTE_FAIL = "POST_FD_TERM_IN_ATTRIBUTE_FAIL"
export const POST_FD_TERM_IN_ATTRIBUTE_SUCCESS =
  "POST_FD_TERM_IN_ATTRIBUTE_SUCCESS"
