export const GEO_FENCING_API_FAIL = "GEO_FENCING_API_FAIL"

// GeoFencings
export const GET_GEO_FENCINGS = "GET_GEO_FENCINGS"
export const GET_GEO_FENCINGS_FAIL = "GET_GEO_FENCINGS_FAIL"
export const GET_GEO_FENCINGS_SUCCESS = "GET_GEO_FENCINGS_SUCCESS"

// Add GeoFencing
export const ADD_GEO_FENCING = "ADD_GEO_FENCING"
export const ADD_GEO_FENCING_FAIL = "ADD_GEO_FENCING_FAIL"
export const ADD_GEO_FENCING_SUCCESS = "ADD_GEO_FENCING_SUCCESS"

// Get GeoFencing
export const GET_GEO_FENCING = "GET_GEO_FENCING"
export const GET_GEO_FENCING_FAIL = "GET_GEO_FENCING_FAIL"
export const GET_GEO_FENCING_SUCCESS = "GET_GEO_FENCING_SUCCESS"

// update GeoFencing
export const PUT_GEO_FENCING = "PUT_GEO_FENCING"
export const PUT_GEO_FENCING_FAIL = "PUT_GEO_FENCING_FAIL"
export const PUT_GEO_FENCING_SUCCESS = "PUT_GEO_FENCING_SUCCESS"

// Delete GeoFencing
export const DELETE_GEO_FENCING = "DELETE_GEO_FENCING"
export const DELETE_GEO_FENCING_FAIL = "DELETE_GEO_FENCING_FAIL"
export const DELETE_GEO_FENCING_SUCCESS = "DELETE_GEO_FENCING_SUCCESS"

// Update Multi GeoFencing Status
export const PUT_GEO_FENCINGS_STATUS = "PUT_GEO_FENCINGS_STATUS"
export const PUT_GEO_FENCINGS_STATUS_FAIL = "PUT_GEO_FENCINGS_STATUS_FAIL"
export const PUT_GEO_FENCINGS_STATUS_SUCCESS = "PUT_GEO_FENCINGS_STATUS_SUCCESS"
