export const GET_USER_REVIEWS = "GET_USER_REVIEWS"
export const GET_USER_REVIEWS_SUCCESS = "GET_USER_REVIEWS_SUCCESS"
export const GET_USER_REVIEWS_FAIL = "GET_USER_REVIEWS_FAIL"

export const GET_USER_ORDERS = "GET_USER_ORDERS"
export const GET_USER_ORDERS_SUCCESS = "GET_USER_ORDERS_SUCCESS"
export const GET_USER_ORDERS_FAIL = "GET_USER_ORDERS_FAIL"