export const CONTENT_PAGE_API_FAIL = "CONTENT_PAGE_API_FAIL"

// CONTENT_PAGEs
export const GET_CONTENT_PAGES = "GET_CONTENT_PAGES"
export const GET_CONTENT_PAGES_FAIL = "GET_CONTENT_PAGES_FAIL"
export const GET_CONTENT_PAGES_SUCCESS = "GET_CONTENT_PAGES_SUCCESS"

// Add CONTENT_PAGE
export const ADD_CONTENT_PAGE = "ADD_CONTENT_PAGE"
export const ADD_CONTENT_PAGE_FAIL = "ADD_CONTENT_PAGE_FAIL"
export const ADD_CONTENT_PAGE_SUCCESS = "ADD_CONTENT_PAGE_SUCCESS"

// Get CONTENT_PAGE
export const GET_CONTENT_PAGE = "GET_CONTENT_PAGE"
export const GET_CONTENT_PAGE_FAIL = "GET_CONTENT_PAGE_FAIL"
export const GET_CONTENT_PAGE_SUCCESS = "GET_CONTENT_PAGE_SUCCESS"

// update CONTENT_PAGE
export const PUT_CONTENT_PAGE = "PUT_CONTENT_PAGE"
export const PUT_CONTENT_PAGE_FAIL = "PUT_CONTENT_PAGE_FAIL"
export const PUT_CONTENT_PAGE_SUCCESS = "PUT_CONTENT_PAGE_SUCCESS"

// Delete CONTENT_PAGE
export const DELETE_CONTENT_PAGE = "DELETE_CONTENT_PAGE"
export const DELETE_CONTENT_PAGE_FAIL = "DELETE_CONTENT_PAGE_FAIL"
export const DELETE_CONTENT_PAGE_SUCCESS = "DELETE_CONTENT_PAGE_SUCCESS"

// Update Multi CONTENT_PAGE Status
export const PUT_CONTENT_PAGES_STATUS = "PUT_CONTENT_PAGES_STATUS"
export const PUT_CONTENT_PAGES_STATUS_FAIL = "PUT_CONTENT_PAGES_STATUS_FAIL"
export const PUT_CONTENT_PAGES_STATUS_SUCCESS =
  "PUT_CONTENT_PAGES_STATUS_SUCCESS"

/* 
****************
Fields
****************
*/
// Add CONTENT_PAGE Field
export const ADD_CONTENT_PAGE_FIELD = "ADD_CONTENT_PAGE_FIELD"
export const ADD_CONTENT_PAGE_FIELD_FAIL = "ADD_CONTENT_PAGE_FIELD_FAIL"
export const ADD_CONTENT_PAGE_FIELD_SUCCESS = "ADD_CONTENT_PAGE_FIELD_SUCCESS"

// Get Document Template
export const GET_CONTENT_PAGE_FIELD = "GET_CONTENT_PAGE_FIELD"
export const GET_CONTENT_PAGE_FIELD_FAIL = "GET_CONTENT_PAGE_FIELD_FAIL"
export const GET_CONTENT_PAGE_FIELD_SUCCESS = "GET_CONTENT_PAGE_FIELD_SUCCESS"

// update Document Template
export const PUT_CONTENT_PAGE_FIELD = "PUT_CONTENT_PAGE_FIELD"
export const PUT_CONTENT_PAGE_FIELD_FAIL = "PUT_CONTENT_PAGE_FIELD_FAIL"
export const PUT_CONTENT_PAGE_FIELD_SUCCESS = "PUT_CONTENT_PAGE_FIELD_SUCCESS"

// Delete Document Template Field
export const DELETE_CONTENT_PAGE_FIELD = "DELETE_CONTENT_PAGE_FIELD"
export const DELETE_CONTENT_PAGE_FIELD_FAIL = "DELETE_CONTENT_PAGE_FIELD_FAIL"
export const DELETE_CONTENT_PAGE_FIELD_SUCCESS =
  "DELETE_CONTENT_PAGE_FIELD_SUCCESS"

// Update Document Template Fields Sorting
export const PUT_CONTENT_PAGE_FIELD_SORT = "PUT_CONTENT_PAGE_FIELD_SORT"
export const PUT_CONTENT_PAGE_FIELD_SORT_FAIL =
  "PUT_CONTENT_PAGE_FIELD_SORT_FAIL"
export const PUT_CONTENT_PAGE_FIELD_SORT_SUCCESS =
  "PUT_CONTENT_PAGE_FIELD_SORT_SUCCESS"
