export const TRANSACTION_API_FAIL = "TRANSACTION_API_FAIL"

// TRANSACTIONs
export const GET_TRANSACTIONS = "GET_TRANSACTIONS"
export const GET_TRANSACTIONS_FAIL = "GET_TRANSACTIONS_FAIL"
export const GET_TRANSACTIONS_SUCCESS = "GET_TRANSACTIONS_SUCCESS"

// Get TRANSACTION
export const GET_TRANSACTION = "GET_TRANSACTION"
export const GET_TRANSACTION_FAIL = "GET_TRANSACTION_FAIL"
export const GET_TRANSACTION_SUCCESS = "GET_TRANSACTION_SUCCESS"

// Export Transactions
export const EXPORT_TRANSACTIONS = "EXPORT_TRANSACTIONS"
export const EXPORT_TRANSACTIONS_FAIL = "EXPORT_TRANSACTIONS_FAIL"
export const EXPORT_TRANSACTIONS_SUCCESS = "EXPORT_TRANSACTIONS_SUCCESS"

// Settlement 
export const GET_SETTLEMENT_LIST = "GET_SETTLEMENT_LIST"
// export const GET_SETTLEMENT_LIST_FAIL = "GET_SETTLEMENT_LIST_FAIL"
export const GET_SETTLEMENT_LIST_SUCCESS = "GET_SETTLEMENT_LIST_SUCCESS"


// Export Transactions
export const WALLET_TRANSACTIONS = "WALLET_TRANSACTIONS"
export const WALLET_TRANSACTIONS_FAIL = "WALLET_TRANSACTIONS_FAIL"
export const WALLET_TRANSACTIONS_SUCCESS = "WALLET_TRANSACTIONS_SUCCESS"
// export wallet transactions

export const EXPORT_WALLET_TRANSACTIONS = "EXPORT_WALLET_TRANSACTIONS"
export const EXPORT_WALLET_TRANSACTIONS_FAIL = "EXPORT_WALLET_TRANSACTIONS_FAIL"
export const EXPORT_WALLET_TRANSACTIONS_SUCCESS = "EXPORT_WALLET_TRANSACTIONS_SUCCESS"
