export const FD_ORDER_API_FAIL = "FD_ORDER_API_FAIL"

// Orders
export const GET_FD_ORDERS = "GET_FD_ORDERS"
export const GET_FD_ORDERS_FAIL = "GET_FD_ORDERS_FAIL"
export const GET_FD_ORDERS_SUCCESS = "GET_FD_ORDERS_SUCCESS"



// Get Order
export const GET_FD_ORDER = "GET_FD_ORDER"
export const GET_FD_ORDER_FAIL = "GET_FD_ORDER_FAIL"
export const GET_FD_ORDER_SUCCESS = "GET_FD_ORDER_SUCCESS"

// Post Refund
export const POST_FD_ORDER_REFUND = "POST_FD_ORDER_REFUND"
export const POST_FD_ORDER_REFUND_FAIL = "POST_FD_ORDER_REFUND_FAIL"
export const POST_FD_ORDER_REFUND_SUCCESS = "POST_FD_ORDER_REFUND_SUCCESS"

// Post Inprocess Order
export const POST_INPROCESS_FD_ORDER = "POST_INPROCESS_FD_ORDER"
export const POST_INPROCESS_FD_ORDER_FAIL = "POST_INPROCESS_FD_ORDER_FAIL"
export const POST_INPROCESS_FD_ORDER_SUCCESS = "POST_INPROCESS_FD_ORDER_SUCCESS"

// Post Accept Order
export const POST_ACCEPT_FD_ORDER = "POST_ACCEPT_FD_ORDER"
export const POST_ACCEPT_FD_ORDER_FAIL = "POST_ACCEPT_FD_ORDER_FAIL"
export const POST_ACCEPT_FD_ORDER_SUCCESS = "POST_ACCEPT_FD_ORDER_SUCCESS"

// Post Reject Order
export const POST_REJECT_FD_ORDER = "POST_REJECT_FD_ORDER"
export const POST_REJECT_FD_ORDER_FAIL = "POST_REJECT_FD_ORDER_FAIL"
export const POST_REJECT_FD_ORDER_SUCCESS = "POST_REJECT_FD_ORDER_SUCCESS"

// Post Order Status
export const POST_FD_ORDER_STATUS = "POST_FD_ORDER_STATUS"
export const POST_FD_ORDER_STATUS_FAIL = "POST_FD_ORDER_STATUS_FAIL"
export const POST_FD_ORDER_STATUS_SUCCESS = "POST_FD_ORDER_STATUS_SUCCESS"

// Dowmload Order PDF
export const EXPORT_ORDER_PDF = "EXPORT_ORDER_PDF"
export const EXPORT_ORDER_PDF_FAIL = "EXPORT_ORDER_PDF_FAIL"
export const EXPORT_ORDER_PDF_SUCCESS = "EXPORT_ORDER_PDF_SUCCESS"



// export order report

// Dowmload Order PDF
export const EXPORT_ORDER_REPORT = "EXPORT_ORDER_REPORT"
export const EXPORT_ORDER_REPORT_FAIL = "EXPORT_ORDER_REPORT_FAIL"
export const EXPORT_ORDER_REPORT_SUCCESS = "EXPORT_ORDER_REPORT_SUCCESS"