export const API_FAIL = "API_FAIL"

// Customers
export const GET_CUSTOMERS = "GET_CUSTOMERS"
export const GET_CUSTOMERS_FAIL = "GET_CUSTOMERS_FAIL"
export const GET_CUSTOMERS_SUCCESS = "GET_CUSTOMERS_SUCCESS"

// Add customer
export const ADD_CUSTOMER = "ADD_CUSTOMER"
export const ADD_CUSTOMER_FAIL = "ADD_CUSTOMER_FAIL"
export const ADD_CUSTOMER_SUCCESS = "ADD_CUSTOMER_SUCCESS"

// Get customer
export const GET_CUSTOMER = "GET_CUSTOMER"
export const GET_CUSTOMER_FAIL = "GET_CUSTOMER_FAIL"
export const GET_CUSTOMER_SUCCESS = "GET_CUSTOMER_SUCCESS"

// update customer
export const PUT_CUSTOMER = "PUT_CUSTOMER"
export const PUT_CUSTOMER_FAIL = "PUT_CUSTOMER_FAIL"
export const PUT_CUSTOMER_SUCCESS = "PUT_CUSTOMER_SUCCESS"

// Delete Customer
export const DELETE_CUSTOMER = "DELETE_CUSTOMER"
export const DELETE_CUSTOMER_FAIL = "DELETE_CUSTOMER_FAIL"
export const DELETE_CUSTOMER_SUCCESS = "DELETE_CUSTOMER_SUCCESS"

// Add Address
export const ADD_CUSTOMER_ADDRESS = "ADD_CUSTOMER_ADDRESS"
export const ADD_CUSTOMER_ADDRESS_FAIL = "ADD_CUSTOMER_ADDRESS_FAIL"
export const ADD_CUSTOMER_ADDRESS_SUCCESS = "ADD_CUSTOMER_ADDRESS_SUCCESS"

// Get Address
export const GET_CUSTOMER_ADDRESS = "GET_CUSTOMER_ADDRESS"
export const GET_CUSTOMER_ADDRESS_FAIL = "GET_CUSTOMER_ADDRESS_FAIL"
export const GET_CUSTOMER_ADDRESS_SUCCESS = "GET_CUSTOMER_ADDRESS_SUCCESS"

// Update Address
export const PUT_CUSTOMER_ADDRESS = "PUT_CUSTOMER_ADDRESS"
export const PUT_CUSTOMER_ADDRESS_FAIL = "PUT_CUSTOMER_ADDRESS_FAIL"
export const PUT_CUSTOMER_ADDRESS_SUCCESS = "PUT_CUSTOMER_ADDRESS_SUCCESS"

// Delete Address
export const DELETE_CUSTOMER_ADDRESS = "DELETE_CUSTOMER_ADDRESS"
export const DELETE_CUSTOMER_ADDRESS_FAIL = "DELETE_CUSTOMER_ADDRESS_FAIL"
export const DELETE_CUSTOMER_ADDRESS_SUCCESS = "DELETE_CUSTOMER_ADDRESS_SUCCESS"

// Update Multi Customers Status
export const PUT_CUSTOMERS_STATUS = "PUT_CUSTOMERS_STATUS"
export const PUT_CUSTOMERS_STATUS_FAIL = "PUT_CUSTOMERS_STATUS_FAIL"
export const PUT_CUSTOMERS_STATUS_SUCCESS = "PUT_CUSTOMERS_STATUS_SUCCESS"

// Export Customers
export const EXPORT_CUSTOMERS = "EXPORT_CUSTOMERS"
export const EXPORT_CUSTOMERS_FAIL = "EXPORT_CUSTOMERS_FAIL"
export const EXPORT_CUSTOMERS_SUCCESS = "EXPORT_CUSTOMERS_SUCCESS"

// Import Customers
export const IMPORT_CUSTOMERS = "IMPORT_CUSTOMERS"
export const IMPORT_CUSTOMERS_FAIL = "IMPORT_CUSTOMERS_FAIL"
export const IMPORT_CUSTOMERS_SUCCESS = "IMPORT_CUSTOMERS_SUCCESS"

// Document
// Get Documents
export const GET_FD_CUSTOMER_DOCUMENTS = "GET_FD_CUSTOMER_DOCUMENTS"
export const GET_FD_CUSTOMER_DOCUMENTS_SUCCESS = "GET_FD_CUSTOMER_DOCUMENTS_SUCCESS"
export const GET_FD_CUSTOMER_DOCUMENTS_FAIL = "GET_FD_CUSTOMER_DOCUMENTS_FAIL"

// Add Document
export const POST_FD_CUSTOMER_DOCUMENT = "POST_FD_CUSTOMER_DOCUMENT"
export const POST_FD_CUSTOMER_DOCUMENT_SUCCESS = "POST_FD_CUSTOMER_DOCUMENT_SUCCESS"
export const POST_FD_CUSTOMER_DOCUMENT_FAIL = "POST_FD_CUSTOMER_DOCUMENT_FAIL"

// Get Document
export const GET_FD_CUSTOMER_DOCUMENT = "GET_FD_CUSTOMER_DOCUMENT"
export const GET_FD_CUSTOMER_DOCUMENT_SUCCESS = "GET_FD_CUSTOMER_DOCUMENT_SUCCESS"
export const GET_FD_CUSTOMER_DOCUMENT_FAIL = "GET_FD_CUSTOMER_DOCUMENT_FAIL"

// Update Document
export const PUT_FD_CUSTOMER_DOCUMENT = "PUT_FD_CUSTOMER_DOCUMENT"
export const PUT_FD_CUSTOMER_DOCUMENT_SUCCESS = "PUT_FD_CUSTOMER_DOCUMENT_SUCCESS"
export const PUT_FD_CUSTOMER_DOCUMENT_FAIL = "PUT_FD_CUSTOMER_DOCUMENT_FAIL"

// Update Document
export const DELETE_FD_CUSTOMER_DOCUMENT = "DELETE_FD_CUSTOMER_DOCUMENT"
export const DELETE_FD_CUSTOMER_DOCUMENT_SUCCESS =
  "DELETE_FD_CUSTOMER_DOCUMENT_SUCCESS"
export const DELETE_FD_CUSTOMER_DOCUMENT_FAIL = "DELETE_FD_CUSTOMER_DOCUMENT_FAIL"
