export const PROMOTION_API_FAIL = "PROMOTION_API_FAIL"

// PROMOTIONs
export const GET_PROMOTIONS = "GET_PROMOTIONS"
export const GET_PROMOTIONS_FAIL = "GET_PROMOTIONS_FAIL"
export const GET_PROMOTIONS_SUCCESS = "GET_PROMOTIONS_SUCCESS"

// Add PROMOTION
export const ADD_PROMOTION = "ADD_PROMOTION"
export const ADD_PROMOTION_FAIL = "ADD_PROMOTION_FAIL"
export const ADD_PROMOTION_SUCCESS = "ADD_PROMOTION_SUCCESS"

// Get PROMOTION
export const GET_PROMOTION = "GET_PROMOTION"
export const GET_PROMOTION_FAIL = "GET_PROMOTION_FAIL"
export const GET_PROMOTION_SUCCESS = "GET_PROMOTION_SUCCESS"

// update PROMOTION
export const PUT_PROMOTION = "PUT_PROMOTION"
export const PUT_PROMOTION_FAIL = "PUT_PROMOTION_FAIL"
export const PUT_PROMOTION_SUCCESS = "PUT_PROMOTION_SUCCESS"

// Delete PROMOTION
export const DELETE_PROMOTION = "DELETE_PROMOTION"
export const DELETE_PROMOTION_FAIL = "DELETE_PROMOTION_FAIL"
export const DELETE_PROMOTION_SUCCESS = "DELETE_PROMOTION_SUCCESS"

// Update Multi PROMOTION Status
export const PUT_PROMOTIONS_STATUS = "PUT_PROMOTIONS_STATUS"
export const PUT_PROMOTIONS_STATUS_FAIL = "PUT_PROMOTIONS_STATUS_FAIL"
export const PUT_PROMOTIONS_STATUS_SUCCESS = "PUT_PROMOTIONS_STATUS_SUCCESS"
