export const EDIT_PROFILE = "EDIT_PROFILE"
export const PROFILE_SUCCESS = "PROFILE_SUCCESS"
export const PROFILE_ERROR = "PROFILE_ERROR"

export const CHANGE_PASSWORD = "CHANGE_PASSWORD"
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS"
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL"

export const POST_ENABLE_NOTIFICATIONS = "POST_ENABLE_NOTIFICATIONS"
export const POST_ENABLE_NOTIFICATIONS_SUCCESS =
  "POST_ENABLE_NOTIFICATIONS_SUCCESS"
export const POST_ENABLE_NOTIFICATIONS_FAIL = "POST_ENABLE_NOTIFICATIONS_FAIL"
