/* USERS */
export const GET_DOMAIN = "GET_DOMAIN"
export const GET_DOMAIN_SUCCESS = "GET_DOMAIN_SUCCESS"
export const GET_DOMAIN_FAIL = "GET_DOMAIN_FAIL"
export const CLEAR_DOMAIN = "CLEAR_DOMAIN"
export const CLEAR_DOMAIN_SUCCESS = "CLEAR_DOMAIN_SUCCESS"

export const BUY_DOMAIN = "BUY_DOMAIN"
export const BUY_DOMAIN_SUCCESS = "BUY_DOMAIN_SUCCESS"
export const BUY_DOMAIN_FAIL = "BUY_DOMAIN_FAIL"
