export const CLEAR_PACKAGE_SERVICE_VENDOR_STORE = "CLEAR_PACKAGE_SERVICE_VENDOR_STORE";

// PACKAGE_SERVICE_VENDOR_LIST
export const GET_PACKAGE_SERVICE_VENDOR_LIST = "GET_PACKAGE_SERVICE_VENDOR_LIST"
export const GET_PACKAGE_SERVICE_VENDOR_LIST_REQUESTED = "GET_PACKAGE_SERVICE_VENDOR_LIST_REQUESTED"
export const GET_PACKAGE_SERVICE_VENDOR_LIST_FAIL = "GET_PACKAGE_SERVICE_VENDOR_LIST_FAIL"
export const GET_PACKAGE_SERVICE_VENDOR_LIST_SUCCESS = "GET_PACKAGE_SERVICE_VENDOR_LIST_SUCCESS"

// Add PACKAGE_SERVICE_VENDOR
export const ADD_PACKAGE_SERVICE_VENDOR = "ADD_PACKAGE_SERVICE_VENDOR"
export const ADD_PACKAGE_SERVICE_VENDOR_REQUESTED = "ADD_PACKAGE_SERVICE_VENDOR_REQUESTED"
export const ADD_PACKAGE_SERVICE_VENDOR_FAIL = "ADD_PACKAGE_SERVICE_VENDOR_FAIL"
export const ADD_PACKAGE_SERVICE_VENDOR_SUCCESS = "ADD_PACKAGE_SERVICE_VENDOR_SUCCESS"

// Get PACKAGE_SERVICE_VENDOR
export const GET_PACKAGE_SERVICE_VENDOR = "GET_PACKAGE_SERVICE_VENDOR"
export const GET_PACKAGE_SERVICE_VENDOR_REQUESTED = "GET_PACKAGE_SERVICE_VENDOR_REQUESTED"
export const GET_PACKAGE_SERVICE_VENDOR_FAIL = "GET_PACKAGE_SERVICE_VENDOR_FAIL"
export const GET_PACKAGE_SERVICE_VENDOR_SUCCESS = "GET_PACKAGE_SERVICE_VENDOR_SUCCESS"

// update PACKAGE_SERVICE_VENDOR
export const PUT_PACKAGE_SERVICE_VENDOR = "PUT_PACKAGE_SERVICE_VENDOR"
export const PUT_PACKAGE_SERVICE_VENDOR_REQUESTED = "PUT_PACKAGE_SERVICE_VENDOR_REQUESTED"
export const PUT_PACKAGE_SERVICE_VENDOR_FAIL = "PUT_PACKAGE_SERVICE_VENDOR_FAIL"
export const PUT_PACKAGE_SERVICE_VENDOR_SUCCESS = "PUT_PACKAGE_SERVICE_VENDOR_SUCCESS"

// Delete PACKAGE_SERVICE_VENDOR
export const DELETE_PACKAGE_SERVICE_VENDOR = "DELETE_PACKAGE_SERVICE_VENDOR"
export const DELETE_PACKAGE_SERVICE_VENDOR_REQUESTED = "DELETE_PACKAGE_SERVICE_VENDOR_REQUESTED"
export const DELETE_PACKAGE_SERVICE_VENDOR_FAIL = "DELETE_PACKAGE_SERVICE_VENDOR_FAIL"
export const DELETE_PACKAGE_SERVICE_VENDOR_SUCCESS = "DELETE_PACKAGE_SERVICE_VENDOR_SUCCESS"

