export const FD_PRODUCT_API_FAIL = "FD_PRODUCT_API_FAIL"

// Products
export const GET_FD_PRODUCTS = "GET_FD_PRODUCTS"
export const GET_FD_PRODUCTS_FAIL = "GET_FD_PRODUCTS_FAIL"
export const GET_FD_PRODUCTS_SUCCESS = "GET_FD_PRODUCTS_SUCCESS"

// Add Product
export const ADD_FD_PRODUCT = "ADD_FD_PRODUCT"
export const ADD_FD_PRODUCT_FAIL = "ADD_FD_PRODUCT_FAIL"
export const ADD_FD_PRODUCT_SUCCESS = "ADD_FD_PRODUCT_SUCCESS"

// Get Product
export const GET_FD_PRODUCT = "GET_FD_PRODUCT"
export const GET_FD_PRODUCT_FAIL = "GET_FD_PRODUCT_FAIL"
export const GET_FD_PRODUCT_SUCCESS = "GET_FD_PRODUCT_SUCCESS"

// update Product
export const PUT_FD_PRODUCT = "PUT_FD_PRODUCT"
export const PUT_FD_PRODUCT_FAIL = "PUT_FD_PRODUCT_FAIL"
export const PUT_FD_PRODUCT_SUCCESS = "PUT_FD_PRODUCT_SUCCESS"

// Delete Product
export const DELETE_FD_PRODUCT = "DELETE_FD_PRODUCT"
export const DELETE_FD_PRODUCT_FAIL = "DELETE_FD_PRODUCT_FAIL"
export const DELETE_FD_PRODUCT_SUCCESS = "DELETE_FD_PRODUCT_SUCCESS"

// Update Multi Product Status
export const PUT_FD_PRODUCTS_STATUS = "PUT_FD_PRODUCTS_STATUS"
export const PUT_FD_PRODUCTS_STATUS_FAIL = "PUT_FD_PRODUCTS_STATUS_FAIL"
export const PUT_FD_PRODUCTS_STATUS_SUCCESS = "PUT_FD_PRODUCTS_STATUS_SUCCESS"

// Export FdProducts
export const EXPORT_FD_PRODUCTS = "EXPORT_FD_PRODUCTS"
export const EXPORT_FD_PRODUCTS_FAIL = "EXPORT_FD_PRODUCTS_FAIL"
export const EXPORT_FD_PRODUCTS_SUCCESS = "EXPORT_FD_PRODUCTS_SUCCESS"

// Import FdRestaurants
export const IMPORT_FD_PRODUCTS = "IMPORT_FD_PRODUCTS"
export const IMPORT_FD_PRODUCTS_FAIL = "IMPORT_FD_PRODUCTS_FAIL"
export const IMPORT_FD_PRODUCTS_SUCCESS = "IMPORT_FD_PRODUCTS_SUCCESS"

// Import FdRestaurantsVariations
export const IMPORT_FD_PRODUCTS_VARIATIONS = "IMPORT_FD_PRODUCTS_VARIATIONS"
export const IMPORT_FD_PRODUCTS_VARIATIONS_FAIL =
  "IMPORT_FD_PRODUCTS_VARIATIONS_FAIL"
export const IMPORT_FD_PRODUCTS_VARIATIONS_SUCCESS =
  "IMPORT_FD_PRODUCTS_VARIATIONS_SUCCESS"

// Import FdRestaurantsVariationsCombine
export const IMPORT_FD_PRODUCTS_COMBINE = "IMPORT_FD_PRODUCTS_COMBINE"
export const IMPORT_FD_PRODUCTS_COMBINE_FAIL = "IMPORT_FD_PRODUCTS_COMBINE_FAIL"
export const IMPORT_FD_PRODUCTS_COMBINE_SUCCESS =
  "IMPORT_FD_PRODUCTS_COMBINE_SUCCESS"
