export const GET_CURRENT_PLAN = "GET_CURRENT_PLAN"
export const GET_CURRENT_PLAN_SUCCESS = "GET_CURRENT_PLAN_SUCCESS"
export const GET_CURRENT_PLAN_FAIL = "GET_CURRENT_PLAN_FAIL"

export const GET_BILLING_PLANS = "GET_BILLING_PLANS"
export const GET_BILLING_PLANS_SUCCESS = "GET_BILLING_PLANS_SUCCESS"
export const GET_BILLING_PLANS_FAIL = "GET_BILLING_PLANS_FAIL"

export const POST_BILLING_CARD = "POST_BILLING_CARD"
export const POST_BILLING_CARD_SUCCESS = "POST_BILLING_CARD_SUCCESS"
export const POST_BILLING_CARD_FAIL = "POST_BILLING_CARD_FAIL"

export const POST_UPGRADE_PLAN = "POST_UPGRADE_PLAN"
export const POST_UPGRADE_PLAN_SUCCESS = "POST_UPGRADE_PLAN_SUCCESS"
export const POST_UPGRADE_PLAN_FAIL = "POST_UPGRADE_PLAN_FAIL"
