export const CAMPAIGN_TEMPLATE_API_FAIL = "CAMPAIGN_TEMPLATE_API_FAIL"

// CampaignTemplate
export const GET_CAMPAIGN_TEMPLATES = "GET_CAMPAIGN_TEMPLATES"
export const GET_CAMPAIGN_TEMPLATES_FAIL = "GET_CAMPAIGN_TEMPLATES_FAIL"
export const GET_CAMPAIGN_TEMPLATES_SUCCESS = "GET_CAMPAIGN_TEMPLATES_SUCCESS"

// Add campaignTemplate
export const ADD_CAMPAIGN_TEMPLATE = "ADD_CAMPAIGN_TEMPLATE"
export const ADD_CAMPAIGN_TEMPLATE_FAIL = "ADD_CAMPAIGN_TEMPLATE_FAIL"
export const ADD_CAMPAIGN_TEMPLATE_SUCCESS = "ADD_CAMPAIGN_TEMPLATE_SUCCESS"

// Get campaignTemplate
export const GET_CAMPAIGN_TEMPLATE = "GET_CAMPAIGN_TEMPLATE"
export const GET_CAMPAIGN_TEMPLATE_FAIL = "GET_CAMPAIGN_TEMPLATE_FAIL"
export const GET_CAMPAIGN_TEMPLATE_SUCCESS = "GET_CAMPAIGN_TEMPLATE_SUCCESS"

// update campaignTemplate
export const PUT_CAMPAIGN_TEMPLATE = "PUT_CAMPAIGN_TEMPLATE"
export const PUT_CAMPAIGN_TEMPLATE_FAIL = "PUT_CAMPAIGN_TEMPLATE_FAIL"
export const PUT_CAMPAIGN_TEMPLATE_SUCCESS = "PUT_CAMPAIGN_TEMPLATE_SUCCESS"

// Delete campaignTemplate
export const DELETE_CAMPAIGN_TEMPLATE = "DELETE_CAMPAIGN_TEMPLATE"
export const DELETE_CAMPAIGN_TEMPLATE_FAIL = "DELETE_CAMPAIGN_TEMPLATE_FAIL"
export const DELETE_CAMPAIGN_TEMPLATE_SUCCESS =
  "DELETE_CAMPAIGN_TEMPLATE_SUCCESS"

// Update Multi CampaignTemplate Status
export const PUT_CAMPAIGN_TEMPLATES_STATUS = "PUT_CAMPAIGN_TEMPLATES_STATUS"
export const PUT_CAMPAIGN_TEMPLATES_STATUS_FAIL =
  "PUT_CAMPAIGN_TEMPLATES_STATUS_FAIL"
export const PUT_CAMPAIGN_TEMPLATES_STATUS_SUCCESS =
  "PUT_CAMPAIGN_TEMPLATES_STATUS_SUCCESS"
