export const FD_REQUEST_API_FAIL = "FD_REQUEST_API_FAIL"

// Orders
export const GET_FD_REQUESTS = "GET_FD_REQUESTS"
export const GET_FD_REQUESTS_FAIL = "GET_FD_REQUESTS_FAIL"
export const GET_FD_PENDING_REQUEST_SUCCESS = "GET_FD_PENDING_REQUEST_SUCCESS"
export const GET_FD_CONFIRMED_REQUEST_SUCCESS =
  "GET_FD_CONFIRMED_REQUEST_SUCCESS"
export const GET_FD_COMPLETED_REQUEST_SUCCESS =
  "GET_FD_COMPLETED_REQUEST_SUCCESS"
export const GET_FD_REJECTED_REQUEST_SUCCESS = "GET_FD_REJECTED_REQUEST_SUCCESS"
export const GET_FD_CANCELLED_REQUEST_SUCCESS =
  "GET_FD_CANCELLED_REQUEST_SUCCESS"

// Get Order
export const GET_FD_REQUEST = "GET_FD_REQUEST"
export const GET_FD_REQUEST_FAIL = "GET_FD_REQUEST_FAIL"
export const GET_FD_REQUEST_SUCCESS = "GET_FD_REQUEST_SUCCESS"

// Post Refund
export const POST_FD_REQUEST_REFUND = "POST_FD_REQUEST_REFUND"
export const POST_FD_REQUEST_REFUND_FAIL = "POST_FD_REQUEST_REFUND_FAIL"
export const POST_FD_REQUEST_REFUND_SUCCESS = "POST_FD_REQUEST_REFUND_SUCCESS"

// Post Accept Order
export const POST_ACCEPT_FD_REQUEST = "POST_ACCEPT_FD_REQUEST"
export const POST_ACCEPT_FD_REQUEST_FAIL = "POST_ACCEPT_FD_REQUEST_FAIL"
export const POST_ACCEPT_FD_REQUEST_SUCCESS = "POST_ACCEPT_FD_REQUEST_SUCCESS"

// Post Reject Order
export const POST_REJECT_FD_REQUEST = "POST_REJECT_FD_REQUEST"
export const POST_REJECT_FD_REQUEST_FAIL = "POST_REJECT_FD_REQUEST_FAIL"
export const POST_REJECT_FD_REQUEST_SUCCESS = "POST_REJECT_FD_REQUEST_SUCCESS"

// Post Ready Order
export const POST_READY_FD_REQUEST = "POST_READY_FD_REQUEST"
export const POST_READY_FD_REQUEST_FAIL = "POST_READY_FD_REQUEST_FAIL"
export const POST_READY_FD_REQUEST_SUCCESS = "POST_READY_FD_REQUEST_SUCCESS"

// Post Complete Order
export const POST_COMPLETE_FD_REQUEST = "POST_COMPLETE_FD_REQUEST"
export const POST_COMPLETE_FD_REQUEST_FAIL = "POST_COMPLETE_FD_REQUEST_FAIL"
export const POST_COMPLETE_FD_REQUEST_SUCCESS =
  "POST_COMPLETE_FD_REQUEST_SUCCESS"

// Post Cancelled Order
export const POST_CANCELLED_FD_REQUEST = "POST_CANCELLED_FD_REQUEST"
export const POST_CANCELLED_FD_REQUEST_FAIL = "POST_CANCELLED_FD_REQUEST_FAIL"
export const POST_CANCELLED_FD_REQUEST_SUCCESS =
  "POST_CANCELLED_FD_REQUEST_SUCCESS"
