export const FD_BUSINESS_TYPE_API_FAIL = "FD_BUSINESS_TYPE_API_FAIL"

// Drivers
export const GET_FD_BUSINESS_TYPES = "GET_FD_BUSINESS_TYPES"
export const GET_FD_BUSINESS_TYPES_FAIL = "GET_FD_BUSINESS_TYPES_FAIL"
export const GET_FD_BUSINESS_TYPES_SUCCESS = "GET_FD_BUSINESS_TYPES_SUCCESS"

// Add Driver
export const ADD_FD_BUSINESS_TYPE = "ADD_FD_BUSINESS_TYPE"
export const ADD_FD_BUSINESS_TYPE_FAIL = "ADD_FD_BUSINESS_TYPE_FAIL"
export const ADD_FD_BUSINESS_TYPE_SUCCESS = "ADD_FD_BUSINESS_TYPE_SUCCESS"

// Get Driver
export const GET_FD_BUSINESS_TYPE = "GET_FD_BUSINESS_TYPE"
export const GET_FD_BUSINESS_TYPE_FAIL = "GET_FD_BUSINESS_TYPE_FAIL"
export const GET_FD_BUSINESS_TYPE_SUCCESS = "GET_FD_BUSINESS_TYPE_SUCCESS"

// update Driver
export const PUT_FD_BUSINESS_TYPE = "PUT_FD_BUSINESS_TYPE"
export const PUT_FD_BUSINESS_TYPE_FAIL = "PUT_FD_BUSINESS_TYPE_FAIL"
export const PUT_FD_BUSINESS_TYPE_SUCCESS = "PUT_FD_BUSINESS_TYPE_SUCCESS"

// Delete Driver
export const DELETE_FD_BUSINESS_TYPE = "DELETE_FD_BUSINESS_TYPE"
export const DELETE_FD_BUSINESS_TYPE_FAIL = "DELETE_FD_BUSINESS_TYPE_FAIL"
export const DELETE_FD_BUSINESS_TYPE_SUCCESS = "DELETE_FD_BUSINESS_TYPE_SUCCESS"

// Update Multi Driver Status
export const PUT_FD_BUSINESS_TYPES_STATUS = "PUT_FD_BUSINESS_TYPES_STATUS"
export const PUT_FD_BUSINESS_TYPES_STATUS_FAIL =
  "PUT_FD_BUSINESS_TYPES_STATUS_FAIL"
export const PUT_FD_BUSINESS_TYPES_STATUS_SUCCESS =
  "PUT_FD_BUSINESS_TYPES_STATUS_SUCCESS"

// Export FdBUSINESSTYPEs
export const EXPORT_FD_BUSINESS_TYPES = "EXPORT_FD_BUSINESS_TYPES"
export const EXPORT_FD_BUSINESS_TYPES_FAIL = "EXPORT_FD_BUSINESS_TYPES_FAIL"
export const EXPORT_FD_BUSINESS_TYPES_SUCCESS =
  "EXPORT_FD_BUSINESS_TYPES_SUCCESS"
