export const GET_DISPUTES = "GET_DISPUTES"
export const GET_DISPUTES_SUCCESS = "GET_DISPUTES_SUCCESS"
export const GET_DISPUTES_FAILED = "GET_DISPUTES_FAILED"

export const GET_DISPUTE = "GET_DISPUTE"
export const GET_DISPUTE_SUCCESS = "GET_DISPUTE_SUCCESS"
export const GET_DISPUTE_FAILED = "GET_DISPUTE_FAILED"

export const POST_DISPUTE_REPLY = "POST_DISPUTE_REPLY"
export const POST_DISPUTE_REPLY_SUCCESS = "POST_DISPUTE_REPLY_SUCCESS"
export const POST_DISPUTE_REPLY_FAILED = "POST_DISPUTE_REPLY_FAILED"

export const DELETE_DISPUTE_REPLY = "DELETE_DISPUTE_REPLY"
export const DELETE_DISPUTE_REPLY_SUCCESS = "DELETE_DISPUTE_REPLY_SUCCESS"
export const DELETE_DISPUTE_REPLY_FAILED = "DELETE_DISPUTE_REPLY_FAILED"

export const PUT_DISPUTE_STATUS = "PUT_DISPUTE_STATUS"
export const PUT_DISPUTE_STATUS_SUCCESS = "PUT_DISPUTE_STATUS_SUCCESS"
export const PUT_DISPUTE_STATUS_FAILED = "PUT_DISPUTE_STATUS_FAILED"