export const PRODUCTS_BATCH_API_FAIL = "PRODUCTS_BATCH_API_FAIL"

// Batch Products
export const GET_PRODUCTS_BATCH = "GET_PRODUCTS_BATCH"
export const GET_PRODUCTS_BATCH_FAIL = "GET_PRODUCTS_BATCH_FAIL"
export const GET_PRODUCTS_BATCH_SUCCESS = "GET_PRODUCTS_BATCH_SUCCESS"

export const ADD_PRODUCTS_BATCH = "ADD_PRODUCTS_BATCH"
export const ADD_PRODUCTS_BATCH_SUCCESS = "ADD_PRODUCTS_BATCH_SUCCESS"
export const ADD_PRODUCTS_BATCH_FAIL = "ADD_PRODUCTS_BATCH_FAIL"

export const GET_PRODUCTS_BATCH_DETAIL = "GET_PRODUCTS_BATCH_DETAIL"
export const GET_PRODUCTS_BATCH_DETAIL_SUCCESS = "GET_PRODUCTS_BATCH_DETAIL_SUCCESS"
export const GET_PRODUCTS_BATCH_DETAIL_FAIL = "GET_PRODUCTS_BATCH_DETAIL_FAIL"
