export const BLOG_CATEGORY_API_FAIL = "BLOG_CATEGORY_API_FAIL"

// BlogCategory
export const GET_BLOG_CATEGORIES = "GET_BLOG_CATEGORIES"
export const GET_BLOG_CATEGORIES_FAIL = "GET_BLOG_CATEGORIES_FAIL"
export const GET_BLOG_CATEGORIES_SUCCESS = "GET_BLOG_CATEGORIES_SUCCESS"

// Add blogCategory
export const ADD_BLOG_CATEGORY = "ADD_BLOG_CATEGORY"
export const ADD_BLOG_CATEGORY_FAIL = "ADD_BLOG_CATEGORY_FAIL"
export const ADD_BLOG_CATEGORY_SUCCESS = "ADD_BLOG_CATEGORY_SUCCESS"

// Get blogCategory
export const GET_BLOG_CATEGORY = "GET_BLOG_CATEGORY"
export const GET_BLOG_CATEGORY_FAIL = "GET_BLOG_CATEGORY_FAIL"
export const GET_BLOG_CATEGORY_SUCCESS = "GET_BLOG_CATEGORY_SUCCESS"

// update blogCategoryyy
export const PUT_BLOG_CATEGORY = "PUT_BLOG_CATEGORY"
export const PUT_BLOG_CATEGORY_FAIL = "PUT_BLOG_CATEGORY_FAIL"
export const PUT_BLOG_CATEGORY_SUCCESS = "PUT_BLOG_CATEGORY_SUCCESS"

// Delete blogCategory
export const DELETE_BLOG_CATEGORY = "DELETE_BLOG_CATEGORY"
export const DELETE_BLOG_CATEGORY_FAIL = "DELETE_BLOG_CATEGORY_FAIL"
export const DELETE_BLOG_CATEGORY_SUCCESS = "DELETE_BLOG_CATEGORY_SUCCESS"

// Update Multi BlogCategory Status
export const PUT_BLOG_CATEGORIES_STATUS = "PUT_BLOG_CATEGORIES_STATUS"
export const PUT_BLOG_CATEGORIES_STATUS_FAIL = "PUT_BLOG_CATEGORIES_STATUS_FAIL"
export const PUT_BLOG_CATEGORIES_STATUS_SUCCESS =
  "PUT_BLOG_CATEGORIES_STATUS_SUCCESS"

//get driver list to assign to dispatcher
export const GET_DRIVER_DISPATCHER_LIST = "GET_DRIVER_DISPATCHER_LIST"
export const GET_DRIVER_DISPATCHER_LIST_SUCCESS =
  "GET_DRIVER_DISPATCHER_LIST_SUCCESS"
export const GET_DRIVER_DISPATCHER_LIST_FAILURE =
  "GET_DRIVER_DISPATCHER_LIST_FAILURE"

//get customer list to assign to dispatcher
export const GET_CUSTOMER_DISPATCHER_LIST = "GET_CUSTOMER_DISPATCHER_LIST"
export const GET_CUSTOMER_DISPATCHER_LIST_SUCCESS =
  "GET_CUSTOMER_DISPATCHER_LIST_SUCCESS"
export const GET_CUSTOMER_DISPATCHER_LIST_FAILURE =
  "GET_CUSTOMER_DISPATCHER_LIST_FAILURE"

export const GET_VENDOR_LIST_SUBADMIN = "GET_VENDOR_LIST_SUBADMIN"
export const GET_VENDOR_LIST_SUBADMIN_SUCCESS = "GET_VENDOR_LIST_SUCCESS"
export const GET_VENDOR_LIST_SUBADMIN_FAILURE =
  "GET_VENDOR_LIST_SUBADMIN_FAILURE"
