export const DOCUMENT_TEMPLATE_API_FAIL = "DOCUMENT_TEMPLATE_API_FAIL"

// Document Templates
export const GET_DOCUMENT_TEMPLATES = "GET_DOCUMENT_TEMPLATES"
export const GET_DOCUMENT_TEMPLATES_FAIL = "GET_DOCUMENT_TEMPLATES_FAIL"
export const GET_DOCUMENT_TEMPLATES_SUCCESS = "GET_DOCUMENT_TEMPLATES_SUCCESS"

// Add Document Template
export const ADD_DOCUMENT_TEMPLATE = "ADD_DOCUMENT_TEMPLATE"
export const ADD_DOCUMENT_TEMPLATE_FAIL = "ADD_DOCUMENT_TEMPLATE_FAIL"
export const ADD_DOCUMENT_TEMPLATE_SUCCESS = "ADD_DOCUMENT_TEMPLATE_SUCCESS"

// Get Document Template
export const GET_DOCUMENT_TEMPLATE = "GET_DOCUMENT_TEMPLATE"
export const GET_DOCUMENT_TEMPLATE_FAIL = "GET_DOCUMENT_TEMPLATE_FAIL"
export const GET_DOCUMENT_TEMPLATE_SUCCESS = "GET_DOCUMENT_TEMPLATE_SUCCESS"

// update Document Template
export const PUT_DOCUMENT_TEMPLATE = "PUT_DOCUMENT_TEMPLATE"
export const PUT_DOCUMENT_TEMPLATE_FAIL = "PUT_DOCUMENT_TEMPLATE_FAIL"
export const PUT_DOCUMENT_TEMPLATE_SUCCESS = "PUT_DOCUMENT_TEMPLATE_SUCCESS"

// Delete Document Template
export const DELETE_DOCUMENT_TEMPLATE = "DELETE_DOCUMENT_TEMPLATE"
export const DELETE_DOCUMENT_TEMPLATE_FAIL = "DELETE_DOCUMENT_TEMPLATE_FAIL"
export const DELETE_DOCUMENT_TEMPLATE_SUCCESS =
  "DELETE_DOCUMENT_TEMPLATE_SUCCESS"

// Update Multi Document Template Status
export const PUT_DOCUMENT_TEMPLATES_STATUS = "PUT_DOCUMENT_TEMPLATES_STATUS"
export const PUT_DOCUMENT_TEMPLATES_STATUS_FAIL =
  "PUT_DOCUMENT_TEMPLATES_STATUS_FAIL"
export const PUT_DOCUMENT_TEMPLATES_STATUS_SUCCESS =
  "PUT_DOCUMENT_TEMPLATES_STATUS_SUCCESS"

/* 
****************
Fields
****************
*/
// Add Document Template Field
export const ADD_DOCUMENT_TEMPLATE_FIELD = "ADD_DOCUMENT_TEMPLATE_FIELD"
export const ADD_DOCUMENT_TEMPLATE_FIELD_FAIL =
  "ADD_DOCUMENT_TEMPLATE_FIELD_FAIL"
export const ADD_DOCUMENT_TEMPLATE_FIELD_SUCCESS =
  "ADD_DOCUMENT_TEMPLATE_FIELD_SUCCESS"

// Get Document Template
export const GET_DOCUMENT_TEMPLATE_FIELD = "GET_DOCUMENT_TEMPLATE_FIELD"
export const GET_DOCUMENT_TEMPLATE_FIELD_FAIL =
  "GET_DOCUMENT_TEMPLATE_FIELD_FAIL"
export const GET_DOCUMENT_TEMPLATE_FIELD_SUCCESS =
  "GET_DOCUMENT_TEMPLATE_FIELD_SUCCESS"

// update Document Template
export const PUT_DOCUMENT_TEMPLATE_FIELD = "PUT_DOCUMENT_TEMPLATE_FIELD"
export const PUT_DOCUMENT_TEMPLATE_FIELD_FAIL =
  "PUT_DOCUMENT_TEMPLATE_FIELD_FAIL"
export const PUT_DOCUMENT_TEMPLATE_FIELD_SUCCESS =
  "PUT_DOCUMENT_TEMPLATE_FIELD_SUCCESS"

// Delete Document Template Field
export const DELETE_DOCUMENT_TEMPLATE_FIELD = "DELETE_DOCUMENT_TEMPLATE_FIELD"
export const DELETE_DOCUMENT_TEMPLATE_FIELD_FAIL =
  "DELETE_DOCUMENT_TEMPLATE_FIELD_FAIL"
export const DELETE_DOCUMENT_TEMPLATE_FIELD_SUCCESS =
  "DELETE_DOCUMENT_TEMPLATE_FIELD_SUCCESS"

// Update Document Template Fields Sorting
export const PUT_DOCUMENT_TEMPLATE_FIELD_SORT =
  "PUT_DOCUMENT_TEMPLATE_FIELD_SORT"
export const PUT_DOCUMENT_TEMPLATE_FIELD_SORT_FAIL =
  "PUT_DOCUMENT_TEMPLATE_FIELD_SORT_FAIL"
export const PUT_DOCUMENT_TEMPLATE_FIELD_SORT_SUCCESS =
  "PUT_DOCUMENT_TEMPLATE_FIELD_SORT_SUCCESS"


// Get Edit Document Template
export const GET_EDIT_DOCUMENT_TEMPLATE_FIELD = "GET_EDIT_DOCUMENT_TEMPLATE_FIELD"
export const GET_EDIT_DOCUMENT_TEMPLATE_FIELD_FAIL =
  "GET_EDIT_DOCUMENT_TEMPLATE_FIELD_FAIL"
export const GET_EDIT_DOCUMENT_TEMPLATE_FIELD_SUCCESS =
  "GET_EDIT_DOCUMENT_TEMPLATE_FIELD_SUCCESS"