/* USERS */
export const GET_CUSTOMERS_REPORTS = "GET_CUSTOMERS_REPORTS"
export const GET_CUSTOMERS_REPORTS_SUCCESS = "GET_CUSTOMERS_REPORTS_SUCCESS"
export const GET_CUSTOMERS_REPORTS_FAIL = "GET_CUSTOMERS_REPORTS_FAIL"
