export const TERMINOLOGY_API_FAIL = "TERMINOLOGY_API_FAIL"

// terminology
export const GET_TERMINOLOGIES = "GET_TERMINOLOGIES"
export const GET_TERMINOLOGIES_FAIL = "GET_TERMINOLOGIES_FAIL"
export const GET_TERMINOLOGIES_SUCCESS = "GET_TERMINOLOGIES_SUCCESS"

// update terminology
export const PUT_TERMINOLOGY = "PUT_TERMINOLOGY"
export const PUT_TERMINOLOGY_FAIL = "PUT_TERMINOLOGY_FAIL"
export const PUT_TERMINOLOGY_SUCCESS = "PUT_TERMINOLOGY_SUCCESS"
