export const GET_STORE_SETTINGS = "GET_STORE_SETTINGS"
export const GET_STORE_SETTINGS_SUCCESS = "GET_STORE_SETTINGS_SUCCESS"
export const GET_STORE_SETTINGS_FAIL = "GET_STORE_SETTINGS_FAIL"

export const PUT_STORE_SETTINGS = "PUT_STORE_SETTINGS"
export const PUT_STORE_SETTINGS_SUCCESS = "PUT_STORE_SETTINGS_SUCCESS"
export const PUT_STORE_SETTINGS_FAIL = "PUT_STORE_SETTINGS_FAIL"

export const GET_MERCHANT_ACCOUNT = "GET_MERCHANT_ACCOUNT"
export const GET_MERCHANT_ACCOUNT_SUCCESS = "GET_MERCHANT_ACCOUNT_SUCCESS"
export const GET_MERCHANT_ACCOUNT_FAILURE = "GET_MERCHANT_ACCOUNT_FAILURE"
