export const CLEAR_USER_TOKEN = "CLEAR_USER_TOKEN"

export const IS_APP_READY = "IS_APP_READY"

export const GET_PUBLIC_DATA = "GET_PUBLIC_DATA"
export const GET_PUBLIC_DATA_SUCCESS = "GET_PUBLIC_DATA_SUCCESS"
export const GET_PUBLIC_DATA_FAIL = "GET_PUBLIC_DATA_FAIL"

export const SUPER_ADMIN_LOGIN = "SUPER_ADMIN_LOGIN"
export const SUPER_ADMIN_LOGIN_SUCCESS = "SUPER_ADMIN_LOGIN_SUCCESS"
export const SUPER_ADMIN_LOGIN_FAIL = "SUPER_ADMIN_LOGIN_FAIL"

export const LOGIN_USER = "LOGIN_USER"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"

export const GET_CURRENT_USER = "GET_CURRENT_USER"
export const GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS"
export const GET_CURRENT_USER_FAIL = "GET_CURRENT_USER_FAIL"

export const LOGOUT_USER = "LOGOUT_USER"
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS"
export const API_ERROR = "LOGIN_API_ERROR"

export const SOCIAL_LOGIN = "SOCIAL_LOGIN"

export const ENABLE_NOTIFICATION = "ENABLE_NOTIFICATION"
export const ENABLE_NOTIFICATION_SUCCESS = "ENABLE_NOTIFICATION_SUCCESS"
export const ENABLE_NOTIFICATION_FAIL = "ENABLE_NOTIFICATION_FAIL"
export const GET_NOTIFICATION_TOKEN = "GET_NOTIFICATION_TOKEN"

export const GET_LANGUAGES = "GET_LANGUAGES"
export const GET_LANGUAGES_SUCCESS = "GET_LANGUAGES_SUCCESS"
export const GET_LANGUAGES_FAIL = "GET_LANGUAGES_FAIL"

export const UPDATE_SOCKET = "UPDATE_SOCKET"
export const UPDATE_SOCKET_SUCCESS = "UPDATE_SOCKET_SUCCESS"
export const UPDATE_SOCKET_FAIL = "UPDATE_SOCKET_FAIL"
